name: CI/CD workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      fail-fast: true
      matrix:
        npm_command:
          [
            "run test:ci",
            "run lint",
            "audit --production --audit-level=critical",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"
      # necessite npm install avant pour création du package-lock
      - name: Install dependencies
        run: npm ci
      - name: exécute les tests
        run: |
          npm ${{ matrix.npm_command }}
